<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Reconstructed4021.Panemonde\Reconstructed4021.Panemonde.csproj" />
    <ProjectReference Include="..\Reconstructed4021.Core\Reconstructed4021.Core.csproj" />
    <ProjectReference Include="..\Reconstructed4021.LegacyNpe\Reconstructed4021.LegacyNpe.csproj" />
  </ItemGroup>

</Project>
