using Reconstructed4021.Core.Combat;
using Reconstructed4021.Core.Types;

namespace Reconstructed4021.Core.Turns;

/// <summary>
/// Owns exactly what Pascal's UpdateTurn owns: play the current empire's turn, move fleets,
/// advance to the next empire, and run the annual tick exactly once per wrap back to the first
/// empire. Human and AI turns go through the same dispatch (game.TurnHandlers), so there's no
/// separate "auto-play the AI empires" path. Since <see cref="Entities.Empire.Status"/> is a
/// permanent-roster field (see docs/EMPIRE_LIFECYCLE_DESIGN.md), this is also the one place
/// dispatch is <see cref="EmpireStatus"/>-aware: an <see cref="EmpireStatus.Active"/> empire plays
/// normally, an <see cref="EmpireStatus.Eliminated"/> one does nothing, and a
/// <see cref="EmpireStatus.PendingElimination"/> one finishes its own deferred teardown here —
/// matching PROLOG.PAS's <c>EmpireNews</c>, which runs at the very start of a defeated player's own
/// next turn.
/// </summary>
/// <remarks>
/// EraseNews (NEWS.PAS) fires right after PlayTurn, matching ANACREON.PAS:246-248's own
/// <c>ImplementNPE(Emp); EraseNews(Emp);</c> sequencing: before this empire's fleets move, so news
/// generated by that movement survives to next turn. The timing matters because
/// <see cref="KingdomTurnHandler"/>'s own ReviewNews reads this news at the start of this empire's
/// next turn: without this ordering, a standing NoFuel item would re-trigger SendRescueFleet every
/// turn forever (ReviewNews has no AlreadyTargetted guard on that path).
/// </remarks>
public sealed class TurnEngine(
    IVisibilityHandler visibility,
    IFleetMovementHandler fleetMovement,
    IAnnualTickHandler annualTick)
{
    /// <summary>
    /// Plays game.CurrentEmpire's turn — via its assigned ITurnHandler, human or AI alike — then
    /// moves fleets, advances CurrentEmpire to the next empire, and runs the annual tick exactly
    /// once per wrap back to the first empire. Mirrors ANACREON.PAS's UpdateTurn (:211-291),
    /// sequential path, one iteration.
    /// </summary>
    public void AdvanceOneTurn(Game game)
    {
        var current = game.CurrentEmpire
            ?? throw new InvalidOperationException("Game.CurrentEmpire must be set before the first turn.");

        switch (current.Status) {
            case EmpireStatus.Active:
                visibility.RefreshVisibility(current, game);
                game.TurnHandlers[current].PlayTurn(current, game);
                current.News.Clear();
                break;

            case EmpireStatus.PendingElimination:
                // EmpireNews (PROLOG.PAS:456-488): this empire's own turn-prologue is where real
                // Pascal finishes the teardown ConquerEmpire's human branch deferred. DefeatedBy was
                // already recorded at PendingElimination time and doesn't change.
                CombatOutcome.DestroyEmpire(current, current.DefeatedBy!, game);
                break;

            case EmpireStatus.Eliminated:
                // InUse stays False forever. Nothing to do -- current still advances below like
                // every other slot, matching Pascal's own fixed-array cycling (see this class's own
                // remarks on why NextEmpire/IsFirstEmpire stay Status-blind).
                break;
        }

        var next = game.NextEmpire(current);
        fleetMovement.AdvanceFleets(game, current, next);
        fleetMovement.AdvanceStarbases(game, next);

        if (game.IsFirstEmpire(next)) {
            annualTick.RunAnnualTick(game);
        }

        game.CurrentEmpire = next;
    }
}
