using Reconstructed4021.Core.Combat;
using Reconstructed4021.Core.Entities;
using Reconstructed4021.Core.Types;

namespace Reconstructed4021.Core.Turns;

/// <summary>
/// Owns exactly what Pascal's UpdateTurn owns: play the current empire's turn, move fleets,
/// advance to the next empire, and run the annual tick exactly once per wrap back to the first
/// empire. Human and AI turns go through the same dispatch (game.TurnHandlers), so there's no
/// separate "auto-play the AI empires" path. Since <see cref="Entities.Empire.Status"/> is a
/// permanent-roster field (see docs/PORT_DESIGN.md's "Empire elimination" section), this is also
/// the one place dispatch is <see cref="EmpireStatus"/>-aware: an <see cref="EmpireStatus.Active"/>
/// empire plays normally, an <see cref="EmpireStatus.Eliminated"/> one does nothing, and a
/// <see cref="EmpireStatus.PendingElimination"/> one finishes its own deferred teardown here —
/// matching PROLOG.PAS's <c>EmpireNews</c>, which runs at the very start of a defeated player's own
/// next turn.
/// </summary>
/// <remarks>
/// EraseNews (NEWS.PAS) fires right after PlayTurn, matching ANACREON.PAS:246-248's own
/// <c>ImplementNPE(Emp); EraseNews(Emp);</c> sequencing: before this empire's fleets move, so news
/// generated by that movement survives to next turn. The timing matters because
/// <see cref="KingdomTurnHandler"/>'s own ReviewNews reads this news at the start of this empire's
/// next turn: without this ordering, a standing NoFuel item would re-trigger SendRescueFleet every
/// turn forever (ReviewNews has no AlreadyTargetted guard on that path).
/// </remarks>
public sealed class TurnEngine(
    IVisibilityHandler visibility,
    IFleetMovementHandler fleetMovement,
    IAnnualTickHandler annualTick)
{
    /// <summary>
    /// game.CurrentEmpire's own turn-prologue: refresh its fog-of-war and dispatch its ITurnHandler
    /// (human or AI alike), or finish a PendingElimination empire's deferred teardown. Mirrors
    /// ANACREON.PAS's SetUpTurn (:183-196) — the source already keeps this separate from
    /// <see cref="EndTurn"/>'s own UpdateTurn (:211-291); this split restores that structure rather
    /// than inventing a new one. A human's own <c>GameShell</c> session runs entirely between this
    /// call and <see cref="EndTurn"/>: <see cref="BeginTurn"/> must run first so their map reflects
    /// fog-of-war as of the start of their turn, not whatever was left over from ending their last
    /// one (the human path used to defer this whole method into "End Turn", which showed them a map
    /// stale by one full round of enemy movement — see docs/OPEN_GAPS.md for how this port's
    /// fog-of-war work found and fixed that ordering bug).
    ///
    /// <see cref="IFleetMovementHandler.ResolveOrders"/> runs here too (<c>allowWait: true</c>) --
    /// this port's own addition, no Pascal equivalent -- right after the fog-of-war refresh and before
    /// this empire ever sees or acts on its own map, so anything its fleets' order queues could resolve
    /// without waiting on physical travel already has (see that method's own doc comment for why this
    /// is one of exactly two points queued orders ever get resolved).
    /// </summary>
    public void BeginTurn(Game game)
    {
        var current = CurrentOrThrow(game);

        switch (current.Status) {
            case EmpireStatus.Active:
                visibility.RefreshVisibility(current, game);
                fleetMovement.ResolveOrders(game, current, allowWait: true);
                game.TurnHandlers[current].PlayTurn(current, game);
                break;

            case EmpireStatus.PendingElimination:
                // EmpireNews (PROLOG.PAS:456-488): this empire's own turn-prologue is where real
                // Pascal finishes the teardown ConquerEmpire's human branch deferred. DefeatedBy was
                // already recorded at PendingElimination time and doesn't change.
                CombatOutcome.DestroyEmpire(current, current.DefeatedBy!, game);
                break;

            case EmpireStatus.Eliminated:
                // InUse stays False forever. Nothing to do here.
                break;
        }
    }

    /// <summary>
    /// game.CurrentEmpire's own turn-epilogue: erase its news, move fleets, advance CurrentEmpire to
    /// the next empire, and run the annual tick exactly once per wrap back to the first empire.
    /// Mirrors ANACREON.PAS's UpdateTurn (:211-291) — EraseNews only fires for a still-Active empire
    /// (:213-222's <c>IF EmpireActive(Player) THEN ... EraseNews(Player)</c>); a PendingElimination
    /// empire's news was already cleared as part of <see cref="Combat.CombatOutcome.DestroyEmpire"/>'s
    /// one-time teardown inside <see cref="BeginTurn"/>, and an already-Eliminated empire generates
    /// none to clear (<see cref="Entities.Empire.AddNews"/> no-ops for it).
    ///
    /// <see cref="IFleetMovementHandler.ResolveOrders"/> also runs here (<c>allowWait: false</c>), right
    /// before <see cref="IFleetMovementHandler.AdvanceFleets"/>/<see cref="IFleetMovementHandler.AdvanceStarbases"/>
    /// -- this empire's own turn-session (whatever ran between <see cref="BeginTurn"/> and this call)
    /// just finished giving orders, so this is where that gets a chance to run this same turn instead of
    /// waiting for the next <see cref="BeginTurn"/>. <c>allowWait: false</c> keeps WAIT costing exactly
    /// one full turn regardless: this call can advance right up to one, never past it.
    ///
    /// This has to come before <see cref="IFleetMovementHandler.AdvanceFleets"/>, not after: a
    /// <see cref="Entities.FleetType.JumpFleet"/> only ever gets its physical step during its own
    /// owner's <see cref="EndTurn"/> (<see cref="IFleetMovementHandler.AdvanceFleets"/>'s
    /// acting-empire branch), so a fresh order queue's DEST resolving after that step already ran left
    /// the fleet loaded and Destination-set but stranded for a full round -- confirmed against a real
    /// autosave (a Resupply-ordered jump fleet sitting <c>InTransit</c> with cargo loaded, having only
    /// started moving turns later). Resolving orders first lets that same DEST's step happen this call.
    /// </summary>
    public void EndTurn(Game game)
    {
        var current = CurrentOrThrow(game);

        if (current.Status == EmpireStatus.Active) {
            current.News.Clear();
        }

        var next = game.NextEmpire(current);

        if (current.Status == EmpireStatus.Active) {
            fleetMovement.ResolveOrders(game, current, allowWait: false);
        }

        fleetMovement.AdvanceFleets(game, current, next);
        fleetMovement.AdvanceStarbases(game, next);

        if (game.IsFirstEmpire(next)) {
            annualTick.RunAnnualTick(game);
        }

        game.CurrentEmpire = next;
    }

    /// <summary>
    /// <see cref="BeginTurn"/> then <see cref="EndTurn"/> back to back, for the common case where
    /// nothing (a human's own interactive session) needs to run between them — every AI turn, and
    /// any test that doesn't care about the split. The TUI's GameShell is the one caller that calls
    /// the two halves separately.
    /// </summary>
    public void AdvanceOneTurn(Game game)
    {
        BeginTurn(game);
        EndTurn(game);
    }

    private static Empire CurrentOrThrow(Game game) =>
        game.CurrentEmpire ?? throw new InvalidOperationException("Game.CurrentEmpire must be set before the first turn.");
}
